### ISSUE TITLE
got CL_INVALID_KERNEL_NAME error

### ISSUE THREAD

**Issue by acanna** [GPGPUCourse2018/Task1AplusB#19]
current status is here 
https://github.com/acanna/Task1AplusB

**Comment by PolarNick239** [comment]
Мелкий момент - https://github.com/acanna/Task1AplusB/blob/master/src/main.cpp#L131-L132 - эти строчки не соответствуют C++ стандарту - см. https://stackoverflow.com/a/15013295

И обратите внимание что [clCreateProgramWithSource](https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clCreateProgramWithSource.html) позволяет передать множество "строчек", но под каждой "строчкой" имеется ввиду не отдельная строка вплоть до переноса каретки, а целый исходный файл. Т.е. в нашем случае т.к. программа состоит из одного исходного файла aplusb.cl - то вам достаточно передать один указатель на char* строчку состоящую из всех символов этого файла (включая символы переноса картеки ```\n```).

Если я недостаточно подробно пояснил - смело спрашивайте.

Помогло?
